main: dev.carloshmfs.playercolorchanger.PlayerColorChanger
name: PlayerColorChanger
version: 0.1
api-version: '1.20'

commands:
  setcolor:
    description: 'Muda a cor na nametag do player'
    usage: '/setcolor <COR>'
